const userConstants = {
	REGISTER_USER: "REGISTER_USER",
	REGISTER_USER_FAIL: "REGISTER_USER_FAIL",

	LOGIN_USER: "LOGIN_USER",
	LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

	LOGOUT: "LOGOUT_USER",

	UPDATE_PRODUCT: "UPDATE_PRODUCT",
	UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",

	GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
	GET_ALL_PRODUCTS_FAIL: "GET_ALL_PRODUCTS_FAIL",

	GET_ERROR: "GET_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
};

export default userConstants;
